name: CI

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CODE_OF_CONDUCT.md'
      - '.editorconfig'
      - '.spi.yml'
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: macOS-14
    strategy:
      matrix:
        destination:
          - "platform=macOS"
          - "platform=macOS,variant=Mac Catalyst"
          - "platform=iOS Simulator,name=iPhone 12"
          - "platform=tvOS Simulator,name=Apple TV"
          - "platform=watchOS Simulator,name=Apple Watch Series 6 (40mm)"
          - "platform=visionOS Simulator,name=Apple Vision Pro"
    steps:
      - uses: actions/checkout@v4
      - name: Test platform ${{ matrix.destination }}
        run: set -o pipefail && xcodebuild -scheme EditorConfig -destination "${{ matrix.destination }}" test | xcbeautify

  linux-test:
    name: Test Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: swift test
